name: ostrohhelpapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.3
  intl: ^0.20.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  http: ^1.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/OAMindCare_logo.png
